# Generated by Django 5.2.7 on 2025-11-22 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JenisKendaraan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('tarif_per_jam', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Kendaraan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_plat', models.CharField(max_length=15, unique=True)),
                ('merk', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('pemilik', models.CharField(max_length=100)),
                ('jenis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkir.jeniskendaraan')),
            ],
        ),
        migrations.CreateModel(
            name='TransaksiParkir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_masuk', models.DateTimeField(auto_now_add=True)),
                ('waktu_keluar', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('masuk', 'Masuk'), ('keluar', 'Keluar')], default='masuk', max_length=10)),
                ('biaya', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('kendaraan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkir.kendaraan')),
            ],
        ),
    ]
